### ISSUE TITLE
Error on quit() method

### ISSUE THREAD

**Issue by stefets** [4br3mm0rd/mpyg321#12]
Hi Emmanuel,

I have an error on the quit() method, this is the output.

I try to figure out how to use pexpect correctly to fix this.

```
from mpyg321.mpyg321 import MPyg321Player
player = MPyg321Player()
player.quit()
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stefets/src/mpyg321/mpyg321/mpyg321.py", line 155, in process_output
    index = self.player.expect(mpg_codes)
  File "/home/stefets/live-config/.venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/home/stefets/live-config/.venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/home/stefets/live-config/.venv/lib/python3.7/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/home/stefets/live-config/.venv/lib/python3.7/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
**pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.**
<pexpect.pty_spawn.spawn object at 0x769c3e10>
command: /usr/local/bin/mpg123
args: ['/usr/local/bin/mpg123', '-R', 'somerandomword']
buffer (last 100 chars): b''
before (last 100 chars): b'@R MPG123 (ThOr) v9\r\nQUIT\r\n\x1b[?25h'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 15892
child_fd: 5
closed: False
timeout: None
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'@P 0')
    1: re.compile(b'@P 1')
    2: re.compile(b'@P 2')
    3: re.compile(b'@P 3')
    4: re.compile(b'@E *')

**Comment by TheTechRobo** [comment]
COuld you surround your code in \`\`\`, like so?

```
>>> print("Hello World")
Hello World
```


It makes it much easier to read

**Comment by stefets** [comment]
More details on my configuration

- mpg123 1.27.2
- Python 3.7.3
- pexpect==4.8.0
- Linux version 5.10.17-v7+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1414 SMP Fri Apr 30 13:18:35 BST 2021

**Comment by 4br3mm0rd** [comment]
I can't reproduce it on macOS, I'll test it in a Linux VM during the weekend.

**Comment by stefets** [comment]
Thanks! It's not a big problem for my setup because I do a SIGINT to stop my script, so mpg123 will handle SIGINT correctly and close gracefully :)

**Comment by 4br3mm0rd** [comment]
This might actually be related to mpg123 (I think I have 321 installed on my mac). I'll try to test this when I have more time (probably by the end of the week, I'm quite busy these days)

**Comment by 4br3mm0rd** [comment]
@stefets has this issue been fixed anytime? Does the quit method still crash on your end?

**Comment by stefets** [comment]
@4br3mm0rd I haven't worked on the problem, but I have a test in mind. I will be working on this problem in the next few days. Currently, the way I use mpg123, the process is terminated via SIGINT from its parent process, so this is not a problem for me but can be a real problem in a use other than mine.

**Comment by stefets** [comment]
> @stefets has this issue been fixed anytime? Does the quit method still crash on your end?

Hey @4br3mm0rd hope you are doing well ? The mpyg321 lib is completely inherited in my mp3 player and it works flawless. I would like to continue to help your to bring your project as the 'Official Python Wrapper for MPG123'

About this issue I have an explanation. It happened on a Raspberry PI with an OS installed on a USB stick. I had extreme IO issues with that configuration. Since I replaced the USB stick with the SD Card there is no more IO issues. 

So I close the ticket since the problem was hardware source.
