### ISSUE TITLE
Automatically set the setup.py version on release

### ISSUE THREAD

**Issue by 4br3mm0rd** [4br3mm0rd/mpyg321#13]
Hi everyone, 

I just created a github action in order to automate the release to Pypi. However, I'd like to automatically setup the version inside of "setup.py" when a GitHub release occurs.

Anyone know what the most efficient way is?

**Comment by TheTechRobo** [comment]
Found this on Reddit: https://github.com/PabloLec/pypi-github-sync

**Comment by 4br3mm0rd** [comment]
Thank you, I'll give it a look (although it seems quite annoying that the update doesn't show up on the repo itself... what do you think?)

**Comment by TheTechRobo** [comment]
> although it seems quite annoying that the update doesn't show up on the repo itself

???

**Comment by 4br3mm0rd** [comment]
> > although it seems quite annoying that the update doesn't show up on the repo itself
> 
> ???

From what I read, this only updates the setup.py which is sent to Pypi, but it doesn't keep the change of value in the repository. This means that when version 2.0 is released, Pypi will receive a setup.py with version 2.0, but on the repo, setup.py will only show the last version that was actually committed by someone (1.1.2 for example)

Or did I misunderstand?

**Comment by TheTechRobo** [comment]
Oh... Yeah, trhat's annoying
