### ISSUE TITLE
Normalize the  remote switch for both players

### ISSUE THREAD

**Issue by stefets** [4br3mm0rd/mpyg321#23]
Both players  must be launch in remote mode. The -R switch is supported by both.

I suggest the use of -R only.

Also, what is the need of the 'test' string after the -R ?

```
def set_player(self, player, audiodevice):
        """Sets the player"""
        player = self.set_version_and_get_player(player)
        //args = "--remote" if self.player_version == "mpg123" else "-R test"
        args = "-R"
```
I have launch mpg123 -R test and it's all fine
```
$ mpg123 -R test
@R MPG123 (ThOr) v9
```

Thanks !

**Comment by 4br3mm0rd** [comment]
mpg321 requires an argument for remote mode (I believe it's the name of a pipe internally)

**Comment by stefets** [comment]
So we could launch the process for both like :

mpg123 -R remote
mpg321 -R remote

**Comment by 4br3mm0rd** [comment]
I think so, need to check for mpg123.
We can also check what happens if we create 2 remote processes with the same name. Is it possible? Will it crash? Will the commands control the same player?
Maybe we would need/be able to add a new feature that allows the user to choose the name (if it has any influence on anything)
I'm quite busy these days but I will try to give it a look next week :)

**Comment by stefets** [comment]
Hi!
This is not urgent and we can make this correct in the future BasePlayer :)
On my side, it's impossible to have two instances of mpg123 running because it exclusively reserve the audiodevice

**Comment by 4br3mm0rd** [comment]
Hey! 
On my end, I was able to run 2 instances of mpg123 using `--remote`, each one was playing its sound, and they went through the speaker together.
Same for mpg321, no matter what the "name" after the `-R` flag is given... The only thing I see is that the mpg321 requires a name after `-R` although it doesn't seem to be using it.

**Comment by stefets** [comment]
Hello!  

After some tests I was able to run 2 instances of the player. It failed when I try to start 2 instances with the --audiodevice parameter to the same card, wich is my production context. First, I was never aware that I can run 2 instances and that's great ! I will investigate on how to be able to run two instances with the -audiodevice switch to the same card.

For the -R switch, I suggest to set the player name as the parameter.

mpg123 -R mpg123
mpg321 -R mpg321

**Comment by 4br3mm0rd** [comment]
Mmh, yeah, why not, I'm not sure if it really makes sense since we don't know what the parameter does, but anyways, this is no big deal :)

**Comment by stefets** [comment]
Yes the problem is that 321 need a parameter, so in order to use -R for both, a dummy parameter has no impact on the 123 side.

Maybe this one ?
mpg123 -R _
mpg321 -R _
