### ISSUE TITLE
Crash when audiodevice is specified

### ISSUE THREAD

**Issue by stefets** [4br3mm0rd/mpyg321#31]
Hi  @4br3mm0rd !

Yesterday I was not completely done on the code and test review and by adjusting my application this morning, there is a crash when the audiodevice parameter is specified.

 ```
args = " --audiodevice " + audiodevice if audiodevice else ""
args += "-R mpyg"   # PROBLEMATIC LINE | A SPACE MUST BE ADD BEFORE THE -R 
 ```

When pexpect crash, it show the command and we cand see that the -R switch is merged with the --audiodevice parameter's value
`args: ['/usr/local/bin/mpg123', '--audiodevice', 'hw:3,0-R', 'mpyg']`

To fix is to a a space before the -R switch
`args += " -R mpyg"`

By fixing it on my side, all of the functionalities I use are stable and works as expected.

Thanks !

**Comment by 4br3mm0rd** [comment]
Oops sorry.

Thanks for the update. Can you PR the fix?

**Comment by stefets** [comment]
Hi,
Of course, PR is created thanks!
