### ISSUE TITLE
Useless condition in MPyg123Player child class

### ISSUE THREAD

**Issue by stefets** [4br3mm0rd/mpyg321#33]
Hi @4br3mm0rd !

I had suggest in the PR #30 which is now close, to remove the condition in the MPyg123Player.py file on line 27.

There is no negative impact at this moment.

In the load_list function.
```
if self.player_version == "mpg123": 
    self.player.sendline("LOADLIST {} {}".format(entry, filepath))
    self.status = PlayerStatus.PLAYING
```

If this is an oversight, I can fix and submit a new PR.

Thanks!

**Comment by 4br3mm0rd** [comment]
I guess we can create a new v2.1 branch and PR to it (I don't think we need to add this fix right now to the code, we can wait for a few more features to get in :) )
