### ISSUE TITLE
How to send an option to the mpg123 player?

### ISSUE THREAD

**Issue by Serendipia2** [4br3mm0rd/mpyg321#34]
I have been testing and the option --rva-mix does exactly what I need (play with replaingains). For instance if I execute mpg123 from bash.
`mpg123 --rva-mix /home/pi/db/Normal.mp3` That song get played slightly quieter because it has a -7.3 db tag.
 
But when I play from python, all songs are played without that option and hence I don't get replaygains.

How can I add the option --rva-mix to the class my player, the one extending my basic player to get. I tried to find a way in the examples and I couldn't and I am unable to figure it out by myself.

Sorry this is not a bug, but I was unsure how to ask the question. Thank you.

**Comment by 4br3mm0rd** [comment]
Hey! Thanks for your contribution!

This is definitely a feature that we could add to this project. In the meantime (until we release it), you can handle gain by using the `player.volume(x)` function.

I will work on this in the upcoming days. I will add both an option in the constructor for this specific parameter, and another option for custom command line parameters so that this kind of issue doesn't occur anymore.

**Comment by Serendipia2** [comment]
That would be great! I don't think I can use the player.volume because I would need to read the replaygain tag, get the value, and although I am sure there is a library that does that, I want to keep the amount of libraries under minimal use. I probably would just wait. I can advance in other aspects of my project in the meanwhile.

Thank you!

**Comment by 4br3mm0rd** [comment]
Hi @RMRubert 
Can you checkout PR #36 and let me know if it works well for you?

**Comment by Serendipia2** [comment]
I might not be doing it right tho, (most likely) but

```
def main():
    """Do the magic"""
    player = MyPlayer(rva_mix=True)
    do_some_play_pause(player)
    sleep(15)
```

gives me:
```
pi@raspberrypi:~ $ /bin/python /home/pi/mpyg321/examples/callbacks.py
Traceback (most recent call last):
  File "/home/pi/mpyg321/examples/callbacks.py", line 69, in <module>
    main()
  File "/home/pi/mpyg321/examples/callbacks.py", line 63, in main
    player = MyPlayer(rva_mix=True)
TypeError: __init__() got an unexpected keyword argument 'rva_mix'
```

**Comment by 4br3mm0rd** [comment]
Mmmmh, that's weird because I have some similar code and it works. I added a full example (in callbacks.py). Can you test the provided example in the last commit and let me know if it works for you?

**Comment by Serendipia2** [comment]
I tried and I didn't manage to make it work:
```
pi@raspberrypi:~/mpyg321 $ /bin/python /home/pi/mpyg321/examples/callbacks.py
Traceback (most recent call last):
  File "/home/pi/mpyg321/examples/callbacks.py", line 72, in <module>
    main()
  File "/home/pi/mpyg321/examples/callbacks.py", line 67, in main
    player = MyPlayer(rva_mix=True)
TypeError: __init__() got an unexpected keyword argument 'rva_mix'
```

But I am not very good with git and check out. Maybe I am just somehow still running the previous version?

**Comment by 4br3mm0rd** [comment]
Which version of Python are you using?

**Comment by Serendipia2** [comment]
I was using the pip version 🤦🏻.

I have unistalled the pip, and used the setup.py and it works perfectly.

**Comment by 4br3mm0rd** [comment]
Alright I will release it

**Comment by Serendipia2** [comment]
Out of curiosity, how long does it take to be on pip? I will be using the checked out version in the meanwhile tho, so not a problem. (It is just that I prefer to have the packages auto-managed)

**Comment by 4br3mm0rd** [comment]
It is live :-)

**Comment by Serendipia2** [comment]
You are a star!

I won't be able to install it today, but I will use and test this library extensively :D
