### ISSUE TITLE
Braking change of issue #31

### ISSUE THREAD

**Issue by stefets** [4br3mm0rd/mpyg321#38]
Hi!

There is a breaking change in the current version that was fixed by me in the issue #31 

In the BasePlayer class, a space must be specified before the -R switch, if not, the -R switch is merged with the audiodevice

Ex.: args: ['/usr/local/bin/mpg123', '--audiodevice', 'plughw:CARD=SD90,DEV=0-R', 'mpyg']

The -R should be a single element of the array

**Comment by 4br3mm0rd** [comment]
Issue solved in v2.1.1
Thank you!

PS: if you write "Resolves #xx" in your PR the issue will be automatically be closed when the PR is merged :)
