### ISSUE TITLE
TypeError: BasePlayer.play_song() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by gnuchanos** [4br3mm0rd/mpyg321#40]
Traceback (most recent call last):
  File "/home/archkubi/.config/qtile/programs/gMusicPlayer.py/gMusicPlayer.py", line 18, in <module>
    music_player.play_song(path="/home/archkubi/.config/qtile/programs/gMusicPlayer.py/Dr_Who_This_Is_Gallifrey.mp3", loop=True)
TypeError: BasePlayer.play_song() missing 1 required positional argument: 'self'

from mpyg321.MPyg123Player import *

music_player = MPyg123Player()
music_player.play_song(path="/home/archkubi/.config/qtile/programs/gMusicPlayer.py/Dr_Who_This_Is_Gallifrey.mp3", loop=True)

i try this but not play sound
from mpyg321.MPyg321Player import MPyg321Player # or MPyg321Player if you installed mpg321
player = MPyg321Player()
player.play_song(path="/home/archkubi/.config/qtile/programs/speech.mp3", loop=True)

**Comment by stefets** [comment]
Hi, your code is correct, I do the same on my side with no issue.
```
from mpyg321.MPyg123Player import MPyg123Player
player = MPyg123Player(audiodevice='U192k')
player.play_song("/home/stefets/Music/so_hard.mp3", True)
time.sleep(10)
player.quit()
```
Cant help more... what is your python and mpyg321 version ?

**Comment by gnuchanos** [comment]
Python 3.11.6
mpyg321 2.1.1

**Comment by 4br3mm0rd** [comment]
This error means that the method is called on a class instead of the instance of the class.
Technically, this would mean that you probably forgot to put parenthesis somewhere. Does your code look like any of the following?
```
player = MPyg123Player # instead of MPyg123Player()
# or 
MPyg123Player.play_song(path="your_path", loop=True) # instead of player.play_song(...)
```

**Comment by gnuchanos** [comment]
last week bruh i remove all code
