### ISSUE TITLE
on_music_end in class to play radio stations triggers randomly

### ISSUE THREAD

**Issue by Serendipia2** [4br3mm0rd/mpyg321#41]
Hi,

I have a code with a class like this, using the 2.1.1 version of mpyg321.MPyg123Player:

```
class radioplayer(MPyg123Player):
    """Class extending basic player"""
    global StationPlayingID
    
    def on_music_end(self):
        time.sleep(1)
        print("?? Event End of song triggered ")
        stationX(StationPlayingID)
```

And I can see how in the middle of the song, the event gets triggered. Is there any way to make it most robust?
thank you.

**Comment by stefets** [comment]
Hi,

This event occurs from mpg123 stdout monitored by the wrapper.

The wrapper does not decide when music stop, the music stop when mpg123 send "@P 0" to stdout

What is your mpg123 version ?

**Comment by Serendipia2** [comment]
apt cache brings me:
```
mpg123:
  Installed: 1.26.4-1
  Candidate: 1.26.4-1
  Version table:
 *** 1.26.4-1 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
```

I also have mpg 321 but I don´t use it:

```
mpg321:
  Installed: (none)
  Candidate: 0.3.2-3.1
  Version table:
     0.3.2-3.1 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
```

**Comment by stefets** [comment]
You can compile the latest mgp123 version and see what happens.

But the best is to bypass the python wrapper and start manually mpg123 in remote mode and observe the stdout stream when the @P 0 message occurs

**Comment by 4br3mm0rd** [comment]
I agree with stefets. Can you please run manually mpg123 on one sound and share the output with us?
