### ISSUE TITLE
loop?

### ISSUE THREAD

**Issue by TheTechRobo** [4br3mm0rd/mpyg321#8]
I need to loop the music in my project, and I can't manually continue looping it; it would make the program take a long time to finish. Is there a way??

**Comment by 4br3mm0rd** [comment]
Hi, 

Thank you for your feedback, I will work on this feature. In the meantime, you can create an onMusicEnd callback (see the "callbacks.py" example).

Something like this:
```
from mpyg321.mpyg321 import MPyg321Player
class MyPlayer(MPyg321Player):
    def onMusicEnd(self):
        self.play_song("/path/to/my/song.mp3");

player = MyPlayer()
player.play_song("/path/to/my/song.mp3")
```

Not tested but should work. Let me know if you have any questions about it while I work on it :)

**Comment by TheTechRobo** [comment]
Would I still be able to stop the music from the usual API (with that code)?

**Comment by 4br3mm0rd** [comment]
It's worth checking, but it should work! :)

**Comment by 4br3mm0rd** [comment]
Deployed as v1.1.0
Thanks for your contribution :-)

**Comment by TheTechRobo** [comment]
Thanks for taking the time to do that!! :D
